apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-ssh
  name: pod-ssh
spec:
  containers:
  - command:
    - sleep
    - Infinity
    image: alpine
    name: pod-ssh
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
        readOnly: true
    
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret

