apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-rs
  labels:
    app: simple
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: simple-label
  template:
    metadata:
      labels:
        tier: simple-label
    spec:
      containers:
      - name: simple-container
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5

