apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: small
  name: small
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: andreimihai/stress
    name: small
    resources: 
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
